### ISSUE TITLE
Unable to start systemd-resolved

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#9]
Somehow _systemctl_ is unable to `start systemd-resolved.service` on Debian 9:

    ERROR:systemctl:no such service 'systemd-resolved.service'

Workaround is to `cp -v /lib/systemd/system/systemd-resolved.service /etc/systemd/system/` but that should not be necessary...

**Comment by gdraheim** [comment]
Why would you want to start that?

In general I am excluding such parts in the general startup behaviour in a docker container.

As for the behaviour: the systemctl.py script looks into /usr/lib/systemd instead of /lib/systemd. That's pretty much all about. ;)

**Comment by onlyjob** [comment]
The correct location is `/lib/systemd/system`. As for why I am trying to start `systemd-resolved.service` (if it is of any relevance) it is to try getting name resolution caching through "nss-resolve". Frankly at this point I'm not sure if it is a viable approach yet...
Regardless, `/etc/systemd/system/` is where _systemctl_ should look for `.service` files first followed by  `/lib/systemd/system`.
Thanks.

**Comment by gdraheim** [comment]
Actually, Debian9 seems to be the only system to have the files in /lib instead of /usr/lib

However the script can take another directory to be searched, so it is not at folder4.

Please check.

**Comment by gdraheim** [comment]
This one can be closed?

**Comment by onlyjob** [comment]
Unfortunately 45128d1 did not fix the problem as you've added `/usr/lib/systemd/system` instead of `/lib/systemd/system`...

**Comment by onlyjob** [comment]
> Actually, Debian9 seems to be the only system to have the files in /lib instead of /usr/lib

Perhaps you meant _Debian_ and (100+) of its derivatives <sup>\[[1],[2],[3]\]</sup> ? ;)
I'd say _Debian_ is the only system that _matters_... :)

[1]: https://en.wikipedia.org/wiki/Debian#Derivatives
[2]: https://wiki.debian.org/Derivatives/Census
[3]: https://www.debian.org/misc/children-distros

**Comment by gdraheim** [comment]
well, just fixed the typo

... it should work now

**Comment by onlyjob** [comment]
Thanks but it still does not work:

    # systemctl start systemd-resolved
    ERROR:systemctl:no such unit: 'resolvconf.conf'

Error disappears after `cp -v /lib/systemd/system/systemd-resolved.service /etc/systemd/system/`.

**Comment by gdraheim** [comment]
The location should not make for a difference, the directories are treated all equal, so that a copy can not have an effect on finding the service or not.

However the error-message is for a completely different unit, and it is not even a service file. That looks quite irritating. You may need to investigate a little more and possibly open another ticket.
